---
# Template configuration files for services

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ services_templates_copy }}"
  when: services_copy_templates
