---
# handlers file for services

- name: services service is restarted
  service:
    name: "{{ service_name }}"
    state: restarted
    sleep: 5
  become: true

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
  become: true
